name: zugantor_repo
description: "Zugantor monorepo root package"
publish_to: 'none'
version: 0.0.1

environment:
  sdk: '>=3.2.3 <4.0.0'

dev_dependencies:
  melos: ^6.3.3
dependencies:
  google_fonts: ^8.0.0
